# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'docker run --rm --privileged multiarch/qemu-user-static:register --reset'
    - task: DOcker@2
      displayName: Login
      inputs:
        command: login
        containerRegistry: "Docker Hub"
    - task: Docker@2
      displayName: Build Pi2AzIot image
      inputs:
        command: buildAndPush
        dockerfile: 'pi2aziot/dockerfile'
        repository: yardbirdsax
        tags: |
          $(tag)