dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    version: 13.2.1
  - name: grafana
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
    version: 6.2.1