apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pi2aziot.fullname" . }}
data:
  iot_connection_string: {{ printf "HostName=%s.azure-devices.net;DeviceId=%s;SharedAccessKey=%s" .Values.iotHub.name .Values.iotHub.deviceName .Values.iotHub.deviceAccessKey | b64enc }}

  
