apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iotprocessor.fullname" . | quote }}
data:
  event_hub_connection_string: {{ .Values.eventHub.connectionString | b64enc | quote }}
  storage_account_key: {{ .Values.storageAccount.key | b64enc | quote }}
