apiVersion: v1
kind: Service
metadata:
  name: {{ include "iotprocessor.fullname" . | quote }}
  annotations:
        prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/name: {{ include "iotprocessor.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - port: 9090
    targetPort: 9090
