name: Build Telegraf Docker image
on:
  push:
    branches:
      - master
    paths:
      - "telegraf/"
jobs:
  buildPushDocker:
    name: Build and Push Docker iamge
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: yardbirdsax/freddy-telegraf
          context: "telegraf/"