name: Build Telegraf Docker image
on:
  push:
    branches:
      - master
    paths:
      - "telegraf/*"
  workflow_dispatch:
    
jobs:
  buildPushDocker:
    name: Build and Push Docker iamge
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yardbirdsax/freddy-telegraf:latest
          context: "telegraf/"